### ISSUE TITLE
Q: where goes repository?

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/CIA#3]
@doutriaux1   Weren't we talking about mving this from gleckler1/CIA => pcmdi/CIA ?  Should we wait a little longer until wheels are thoroughly greased?

**Comment by doutriaux1** [comment]
I made you admin, you can move the repo whenever you want.

**Comment by gleckler1** [comment]
@doutriaux1 thnks!  time to roll up my sleeves and do damage.
