### ISSUE TITLE
cdp example not working...

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/CIA#6]
@doutriaux1 @zshaheen   I'm having problems with last example in
https://github.com/PCMDI/CIA/blob/master/demo/CIA_Examples.ipynb
Files I'm trying to use are in https://github.com/PCMDI/CIA/blob/master/demo
But getting close!   Lets try to knock this off tomorrow.
P

**Comment by zshaheen** [comment]
@gleckler1 Can you explain to @doutriaux1 and I what the errors/problems are?

**Comment by gleckler1** [comment]
@zshaheen @doutriaux1  too many meetings today, blea... hope to be back on this at 4PM.  I'll try to explain remaining issues.

**Comment by doutriaux1** [comment]
no worries

**Comment by gleckler1** [comment]
@zshaheen @doutriaux1 ok... PG still struggling.  I have an environment on oceanonly where the following works:
> python test2.py -p test_paramfile.py
> some/mod/path
> hi super looser
> bad

On my mac I've just installed cdp and cia via
> conda create -n cdpcia cia -c pcmdi
then
> conda install cdp -c conda-forge -c uvcdat
both installed successfully.   But when I try to run it on the mac:
(cdpcia) bash-3.2$ python test2.py -p test_paramfile.py
Traceback (most recent call last):
  File "test2.py", line 25, in <module>
    params = P.get_parameter()
  File "/Users/gleckler1/anaconda2/lib/python2.7/site-packages/cdp/cdp_parser.py", line 324, in get_parameter
    return self.get_parameters(*args, **kwargs)[0]
  File "/Users/gleckler1/anaconda2/lib/python2.7/site-packages/cdp/cdp_parser.py", line 295, in get_parameters
    orig_parameters = self.get_orig_parameters(default_vars=default_vars, cmd_default_vars=cmd_default_vars, *args, **kwargs)
  File "/Users/gleckler1/anaconda2/lib/python2.7/site-packages/cdp/cdp_parser.py", line 80, in get_orig_parameters
    if not self.__args_namespace.parameters:
AttributeError: 'Namespace' object has no attribute 'parameters'

ANY HINTS?

**Comment by doutriaux1** [comment]
you need -c pcmdi/label/nighlty -c pcmdi I think.

**Comment by doutriaux1** [comment]
actually no you don't forget this

**Comment by doutriaux1** [comment]
`conda list cdp` please

**Comment by gleckler1** [comment]
@doutriaux1 
(cdpcia) bash-3.2$ conda list cdp
# packages in environment at /Users/gleckler1/anaconda2/envs/cdpcia:
#
# Name                    Version                   Build  Channel
(cdpcia) bash-3.2$

**Comment by zshaheen** [comment]
@gleckler1 Can you post the contents of your `test2.py` and `test_paramfile.py`?

**Comment by gleckler1** [comment]
@zshaheen They are now in https://github.com/PCMDI/CIA/tree/master/demo

**Comment by gleckler1** [comment]
@zshaheen @doutriaux1  I think the commands I mentioned I used on osx above might be an issue... after I created cdpcia,  I should have activated that env before 
conda install cdp -c conda-forge -c uvcdat

retrying now...

**Comment by gleckler1** [comment]
@zshaheen @doutriaux1  First suspicion should be PG does not know what he is doing, but...
I have reinstalled on osx and after converting print statement to python3...

(cdpcia_022318) bash-3.2$ python test2.py -p test_paramfile.py
  File "test2.py", line 27
    print params.modpath
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(params.modpath)?
(cdpcia_022318) bash-3.2$ vim test2.py
(cdpcia_022318) bash-3.2$
(cdpcia_022318) bash-3.2$
(cdpcia_022318) bash-3.2$ python test2.py -p test_paramfile.py
Traceback (most recent call last):
  File "test2.py", line 25, in <module>
    params = P.get_parameter()
  File "/Users/gleckler1/anaconda2/envs/cdpcia_022318/lib/python3.6/site-packages/cdp/cdp_parser.py", line 324, in get_parameter
    return self.get_parameters(*args, **kwargs)[0]
  File "/Users/gleckler1/anaconda2/envs/cdpcia_022318/lib/python3.6/site-packages/cdp/cdp_parser.py", line 295, in get_parameters
    orig_parameters = self.get_orig_parameters(default_vars=default_vars, cmd_default_vars=cmd_default_vars, *args, **kwargs)
  File "/Users/gleckler1/anaconda2/envs/cdpcia_022318/lib/python3.6/site-packages/cdp/cdp_parser.py", line 80, in get_orig_parameters
    if not self.__args_namespace.parameters:
AttributeError: 'Namespace' object has no attribute 'parameters'

Jupyter now working for me on oceanonly so I can continue to advance things there... so is just an FYI that something seems to be fishy on osx.

**Comment by gleckler1** [comment]
@zshaheen @doutriaux1  Actually,  notebooks are too clunky on oceanonly so am going to revert back to developing this on my mac.   Which means I do hope to solve as soon as possible this problem of the example above not working on osx.

**Comment by gleckler1** [comment]
@zshaheen @doutriaux1  can you guys pls help me getting this working on osx tomorrow.  I want to complete a first version of the demo/notebook but I need to do that from mac.    thanks
